In [ ]:
# Bismillah

In [6]:
import numpy as np
import pandas as pd

# The Series
    * A one-dimensional array
    * Holds a single data type
    * Allows access to elements through the associated index labels - helps in allignment of multiple series.

In [7]:
np.random.randn(100) # numpy array

array([ 2.45842812, -1.09927784,  1.75794182,  0.29568844,  0.10416013,
       -1.53068833,  0.2262879 , -0.93053316, -1.490674  ,  1.16376726,
       -0.14402236,  0.26581212,  0.35289843,  1.72917056,  0.13901108,
        0.46786682, -0.16786839, -1.29132587,  1.25042854,  1.1570309 ,
        0.09204988,  0.55107283,  1.4828191 ,  0.21825823, -1.09276219,
       -1.08408525, -1.3936341 ,  0.16389215, -0.61980219, -0.18667651,
        0.14170288, -0.66175889,  0.14794195,  1.3735017 , -0.53350615,
       -0.98426898,  0.39752415,  0.13295949, -0.4416634 ,  0.01997714,
       -0.96890536, -1.01473467,  0.16021566, -0.11350545, -1.07896334,
       -0.76317923,  0.72658884,  2.10392993, -1.08506142, -1.42142261,
       -0.29939207, -0.07313668, -0.32639995, -0.84478693, -1.04672266,
        0.39598098,  0.56727632, -1.03642924,  1.5547316 , -0.05614963,
       -1.67302721, -1.46633268,  0.95690802, -0.02373472, -2.85265276,
       -0.08449829,  0.98501326,  0.49044209,  0.91610793, -1.57

In [10]:
s = pd.Series(np.random.randn(100)) # pandas series

In [11]:
s

0    -2.525427
1     0.652383
2     0.986300
3    -1.291662
4     1.325174
        ...   
95    1.934394
96    0.893534
97    1.121842
98   -1.945747
99   -1.087411
Length: 100, dtype: float64

In [12]:
s[2] # grab a value located at index 2.

0.986299801118016

In [ ]:
# s[2, 4] # error since no single index, 2 4, exists.

In [14]:
s[[2, 4,3]] # the inner [] indicates multiple indices given.

2    0.986300
4    1.325174
3   -1.291662
dtype: float64

In [15]:
s[5:10] # slicing doesn't need [] since there is no confusion.

5    0.205265
6    0.550818
7   -0.910759
8   -0.299291
9    0.229892
dtype: float64

In [16]:
s.head()

0   -2.525427
1    0.652383
2    0.986300
3   -1.291662
4    1.325174
dtype: float64

In [17]:
s.tail()

95    1.934394
96    0.893534
97    1.121842
98   -1.945747
99   -1.087411
dtype: float64

In [18]:
s.shape # 100 rows. Attribute and not method.

(100,)

In [19]:
s.index # Attribute and not method.

RangeIndex(start=0, stop=100, step=1)

In [20]:
s.values

array([-2.52542666,  0.65238262,  0.9862998 , -1.29166197,  1.32517403,
        0.20526497,  0.55081784, -0.91075911, -0.29929144,  0.2298921 ,
        1.07864202,  0.28884326, -0.8422935 ,  1.40883841, -1.09787138,
        0.77496537, -0.55062069, -1.11035171, -1.84218659,  0.8051206 ,
        1.50599236,  0.41081781, -0.63583328,  0.53357653,  0.2216532 ,
       -0.74940697,  0.31491869, -1.09282529, -0.22812831, -0.9651645 ,
        0.08010999, -0.24074059,  0.48909379, -0.51694059, -0.17317819,
       -0.73606676, -0.25009487,  0.06984677, -1.29535581,  1.12271243,
       -0.13433756,  1.3576567 ,  1.34599561,  1.19530057,  0.02221367,
       -0.12908414, -1.1052334 , -1.70757764,  0.24028376, -0.4959476 ,
        0.12451892,  0.61750057, -1.35874227,  0.91941547,  0.81706771,
       -1.99823174, -0.16390672,  0.92483617, -1.959562  ,  0.19150821,
       -1.77510182,  0.73607738, -0.28994434,  0.61552421, -1.20523303,
       -0.33515205, -1.18688033, -1.6450919 ,  2.33815378, -1.25

In [21]:
s = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd']) 
# [] to indicate multiple values as usual. Indices assigned at the time of constructing a series.
# Series created through a list.

In [22]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [23]:
s = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})
# Series created through a dictionary. The keys are the indices in the series.

In [24]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [25]:
s = pd.Series([1, 2, 3, 4, np.nan])
# np.nan so that the pandas know that this value is missing.

In [26]:
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [27]:
len(s)
# includes a missing avalue as well.

5

In [28]:
s.count()
# excludes missing value.

4

In [29]:
s = pd.Series([10, 3 , 4, 5, 7, 7, 9, 10, np.nan])

In [30]:
s

0    10.0
1     3.0
2     4.0
3     5.0
4     7.0
5     7.0
6     9.0
7    10.0
8     NaN
dtype: float64

In [31]:
s.unique()
# returns only unique values. That is, avoid repeatition of the same value.
# returns the missing value as well.

array([10.,  3.,  4.,  5.,  7.,  9., nan])

In [32]:
s.value_counts()
# returns frrequency distribution in descending order. For ascending order, ascending = True.
# excludes a missing value.

10.0    2
7.0     2
3.0     1
4.0     1
5.0     1
9.0     1
dtype: int64

In [33]:
s.value_counts(ascending = True) # go from smaller values to larger values.

3.0     1
4.0     1
5.0     1
9.0     1
10.0    2
7.0     2
dtype: int64

In [34]:
s.value_counts(normalize = True) # to grab percentages. ascending = False is the default argument.


10.0    0.250
7.0     0.250
3.0     0.125
4.0     0.125
5.0     0.125
9.0     0.125
dtype: float64

In [38]:
s1 = pd.Series([1, 2, 3,4], index = ['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index = ['d', 'c', 'b', 'a'])

In [39]:
s1 + s2
# The allignment is done automatically on the basis of index labels.
# This feature does not exist in numpy array. See below.

a    2
b    4
c    6
d    8
dtype: int64

In [40]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])

In [41]:
a1

array([1, 2, 3, 4])

In [42]:
a2

array([4, 3, 2, 1])

In [43]:
a1 + a2
# each corresponding element from both the arrays must be added. No flexibility of adding any two desriable elements of
# array located at different indices.

array([5, 5, 5, 5])